### ISSUE TITLE
not working in updating "MB User Meta"

### ISSUE THREAD

**Issue by devjiro76** [wpmetabox/mb-rest-api#12]
I purchased "MB USER META" and installed well.

I setup the "MB USER META Fields" like below.
![image](https://user-images.githubusercontent.com/25057349/54493243-e615bf00-4910-11e9-93ce-8a9501fd1766.png)
(I can see the proper fields in Profile Page(admin) and when I modify data in DB, it looks well in the admin page)

but update user meta data with rest-api, this is not work.
for example.
![image](https://user-images.githubusercontent.com/25057349/54493275-37be4980-4911-11e9-8fc0-ae72d0a2fda5.png)

this "POST Method Request" is not work.

PS.
I tested "mb-rest-api" with other type (like post) this was worked.
only with "user" wasn't work.
I checked so many times "post method" "application/json" type in header... etc...

**Comment by rilwis** [comment]
Fixed in 96fc07db6341ed5caf42f59db1871d6d9f6ce5e4
