### ISSUE TITLE
Get the data of MB Settings Pages via REST APIs

### ISSUE THREAD

**Issue by ghoshnirmalya** [wpmetabox/mb-rest-api#14]
Currently, there is no way to fetch the data for the MB Settings Pages via the REST APIs. I came across [this old support ticket](https://support.metabox.io/topic/mb-settings-page-in-rest-api/) which states that the settings values are not sent to the REST API via MB REST API.

I'd like to know if there is a way through which we can get the data of the MB Settings Pages via REST APIs.

**Comment by rilwis** [comment]
Hi @ghoshnirmalya 

We'll try to add this feature. Currently, I imagine we can use the API to get the option to get the values as they're saved in normal WP option.
