### ISSUE TITLE
On POST, WP 4.7.3 seems to pass an object rather than a JSON string?

### ISSUE THREAD

**Issue by btsimonh** [wpmetabox/mb-rest-api#4]
line 84 complains that json_decode is being passed an array rather than a json string.
A quick debug showed this.  Maybe they changed something in WP 4.7.3?
Also, if any of the meta-box fields is an array or an object, then strip_tags() complains, and the content of the array/object is destroyed on POST.  so either way, writing meta-box data this way is currently broken.

**Comment by btsimonh** [comment]
Added a pull request which works for me....

**Comment by rilwis** [comment]
I've just merged your PR. It requires the [development version](https://github.com/rilwis/meta-box) of Meta Box to work. Can you check it please?

PS: Thanks for your contribution!
