### ISSUE TITLE
Filter fields

### ISSUE THREAD

**Issue by JulianoSenfft** [wpmetabox/mb-rest-api#7]
Any idea how to filter the fields?

I'm trying to use filter[meta_query][0][key]=post_id&filter[meta_query][0][value]=77 but it does not apply any filter.

I'm using the rest-filter-master plugin

Thanks!

**Comment by radeno** [comment]
@JulianoSenfft you need to ask in https://github.com/WP-API/rest-filter
MetaBox REST API plugin just returns  registered meta fields
